apiVersion: v1
kind: ConfigMap
metadata: 
  name: pgadmin-config
data: 
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "mydb",
          "Group": "Servers",
          "Port": 30432,
          "Username": "root",
          "Host": "192.168.46.41",
          "MaintenanceDB": "postgres",
          "ConnectionParameters": {
            "sslmode": "prefer",
            "passfile": "/var/lib/storage/.pgpass",
            "connect_timeout": 10
          }
        }
      }
    }
  .pgpass: |
    192.168.46.41:30432:*:root:POcoco12PO
