fullnameOverride: "postgresql"
global:
  security:
    allowInsecureImages: true
  postgresql:
    auth:
      postgresPassword: "password"
    service:
      ports:
        postgresql: "5432"

image:
  registry: registry-1.docker.io
  repository: bitnamilegacy/postgresql:17.6.0
  # tag: 18.1.11
  digest: "sha256:94c148526e3de5a414cc53f75701ed0d57ff3719466851723512fcbd1182522a"
